### ISSUE TITLE
第4章app.js的问题

### ISSUE THREAD

**Issue by DetaiLC** [phodal/designiot-books#3]
你好，我是一个完全的新手，我再ubuntu上运行第4章的内容中遇到了两个困难。
第一个，我想问一下第4章一开始写的那个app.js我运行node app.js以后该怎么操作才能执行get 和post
第二个，这个node app.js以后我用control + Z 关闭后再运行node app.js会出现8080端口被占用的问题，应该如何正确操作
如果能帮助我，非常感谢。

**Comment by DetaiLC** [comment]
你好，前面的问题我已经解决，但是再我进行

```
curl -X PUT -d '{ "led": true }' -H "Conten-Type: application/json" http://127.0.0.1:7070/api/1
curl: (52) Empty reply from server
```

时出现了这样的错误：

```
/home/hff/Documents/WWW/myapp/node_modules/mongodb/lib/mongo_client.js:224
          throw err
          ^

TypeError: Cannot read property 'collection' of null
    at findDocuments (/home/hff/Documents/WWW/myapp/dbb:43:32)
    at /home/hff/Documents/WWW/myapp/dbb:49:9
    at connectCallback (/home/hff/Documents/WWW/myapp/node_modules/mongodb/lib/mongo_client.js:314:5)
    at /home/hff/Documents/WWW/myapp/node_modules/mongodb/lib/mongo_client.js:221:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by DetaiLC** [comment]
普通的使用网页上进行修改时没问题的

**Comment by phodal** [comment]
@DetaiLC 打错字了~~ Content-Type

**Comment by DetaiLC** [comment]
好吧- -我傻了谢谢0 0
那能不能再问一个问题第5章里面使用ESP8266的时候，在void loop中有
char c = client.read();
print(c);
我想写一个if, 判断这里的c是[{"_id":"58690e1e67080a200cb352d0","user":"1","led":true}]还是
[{"_id":"58690e1e67080a200cb352d0","user":"1","led":false}]
我不太清楚这里c的数据类型，一直写不对
谢谢帮助我 - -
